name: Deploy Project
on: [push, workflow_dispatch]
jobs: 
  build:
    runs-on: ubuntu-22.04
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Set up JDK1.8
        uses: actions/setup-java@v3
        with: 
          distribution: 'corretto'
          java-version: '8'
          cache: maven
      - name: Build with maven
        run: mvn -B package --file pom.xml